# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m venv test_env
        source test_env/bin/activate
      # see: https://community.intel.com/t5/Processors/Using-OpenCL-in-GitHub-Actions-running-on-windows/m-p/1498635
    - name: Setup OpenCL
      run: |
        sudo apt-get update
        sudo apt-get install -y ocl-icd-opencl-dev
        sudo apt-get install -y pocl-opencl-icd
    - name: Install dependencies
      run: |
        source test_env/bin/activate
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # NOTE: This would be a nice step but it's looking into dependencies and failing.
    #       For now disable this.
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Editable install danpy package
      run: |
        source test_env/bin/activate
        pip install -e .
    - name: Test with pytest
      run: |
        source test_env/bin/activate
        pytest src/tests
